# Generated by Django 4.0.4 on 2022-05-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Mlwebapp',
        ),
    ]
