# Generated by Django 4.0.4 on 2022-06-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlweb', '0002_rename_todo_mlwebapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
    ]
